version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    container_name: rails_start_app
    hostname: rails_start_app
    volumes:
      - rails_start_app_volume:/app:nocopy
    volumes_from:
      - data
    depends_on:
      - db
    ports:
      - 3000:3000
    env_file:
      - ./.docker/.docker_env
    environment:
      - RAILS_ENV=development
    tty: true
    stdin_open: true
  db:
    image: mysql:latest
    container_name: rails_start_db
    hostname: rails_start_db
    volumes:
      - ./.docker/db/myconf.d/:/etc/mysql/conf.d/
    volumes_from:
      - data
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=app_development
      - MYSQL_ROOT_PASSWORD=root
  data:
    image: busybox
    container_name: rails_start_data
    hostname: rails_start_data
    volumes:
      - rails_start_app_bundle_volume:/usr/local/bundle:rw
      - rails_start_app_db_volume:/var/lib/mysql:rw

volumes:
  rails_start_app_db_volume:
    driver: local
  rails_start_app_bundle_volume:
    driver: local
  rails_start_app_volume:
    external: true
